<?php

/*

    Project: 
    using code from RoadsEnd PHP SiteManager
	
    description   : site wide global helper functions

    change history:
            
                xx/xx/01 - script created by xxxx
                    
*/

/** user login handler */
/*
function userHandler($isMember, &$dbR) {

    if ($isMember) {

        // user is a valid member, with a valid session

    }
    else {

        // user is a guest


    }

}
*/

?>